from datetime import datetime

from PySide2.QtCore import (QCoreApplication, QDate, QMetaObject,
                            QRect, QSize, QTime, Qt)
from PySide2.QtGui import (QCursor, QFont,
                           QIcon)
from PySide2.QtWidgets import *
from PySide2.QtWidgets import QAction, QWidget, QToolBox, QToolBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(600, 550)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(600, 550))
        MainWindow.setToolTipDuration(1)

        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.guideModel = QAction(MainWindow)
        self.guideModel.setObjectName(u"guideModel")
        self.guideDepartments = QAction(MainWindow)
        self.guideDepartments.setObjectName(u"guideDepartments")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.toolBox = QToolBox(self.centralwidget)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(10, 10, 580, 440))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy1)
        self.toolBox.setMinimumSize(QSize(0, 0))
        self.toolBox.setSizeIncrement(QSize(0, 0))
        self.toolBox.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setFamily(u"Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QCursor(Qt.ArrowCursor))
        self.toolBox.setFocusPolicy(Qt.NoFocus)
        self.toolBox.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.toolBox.setToolTipDuration(0)
        self.toolBox.setLayoutDirection(Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setInputMethodHints(Qt.ImhNone)
        self.toolBox.setFrameShape(QFrame.NoFrame)
        self.toolBox.setFrameShadow(QFrame.Plain)
        self.toolBox.setLineWidth(0)

        #---------------------------page_1--------------------------------#
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 580, 342))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setWeight(50)
        font1.setKerning(True)
        self.page.setFont(font1)
        self.page.setToolTipDuration(0)
        self.page.setAutoFillBackground(True)

        self.pB_clear_filter = QPushButton(self.page)
        self.pB_clear_filter.setObjectName(u"pB_clear_filter")
        self.pB_clear_filter.setGeometry(QRect(440, 0, 141, 23))
        self.pB_save = QPushButton(self.page)
        self.pB_save.setObjectName(u"pB_save")
        self.pB_save.setEnabled(True)
        self.pB_save.setGeometry(QRect(510, 280, 70, 23))

        self.tableView_select = QTableView(self.page)
        self.tableView_select.setObjectName(u"tableView_select")
        self.tableView_select.setGeometry(QRect(0, 90, 580, 181))
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tableView_select.sizePolicy().hasHeightForWidth())
        self.tableView_select.setSizePolicy(sizePolicy2)
        self.tableView_select.setToolTipDuration(0)
        self.tableView_select.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableView_select.setAutoScroll(True)
        self.tableView_select.setEditTriggers(QAbstractItemView.AnyKeyPressed | QAbstractItemView.DoubleClicked | QAbstractItemView.EditKeyPressed)
        self.tableView_select.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tableView_select.setTextElideMode(Qt.ElideMiddle)
        self.tableView_select.setVerticalScrollMode(QAbstractItemView.ScrollPerItem)
        self.tableView_select.setGridStyle(Qt.DashLine)
        self.tableView_select.verticalHeader().setVisible(False)

        self.pB_add = QPushButton(self.page)
        self.pB_add.setObjectName(u"pB_add")
        self.pB_add.setGeometry(QRect(0, 280, 40, 30))
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.pB_add.sizePolicy().hasHeightForWidth())
        self.pB_add.setSizePolicy(sizePolicy3)
        icon = QIcon()
        icon.addFile("images/add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pB_add.setIcon(icon)

        self.lineEdit = QLineEdit(self.page)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QRect(110, 0, 180, 20))
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QLineEdit.Normal)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setClearButtonEnabled(True)

        self.pB_delete = QPushButton(self.page)
        self.pB_delete.setObjectName(u"pB_delete")
        self.pB_delete.setGeometry(QRect(100, 280, 40, 30))
        icon1 = QIcon()
        icon1.addFile("images/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pB_delete.setIcon(icon1)

        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 90, 20))
        self.label.setFrameShape(QFrame.NoFrame)

        self.comboBox_model = QComboBox(self.page)
        self.comboBox_model.setObjectName(u"comboBox_model")
        self.comboBox_model.setGeometry(QRect(110, 30, 180, 20))
        self.comboBox_model.setFocusPolicy(Qt.ClickFocus)

        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 30, 101, 16))
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 60, 61, 16))

        self.comboBox_status = QComboBox(self.page)
        self.comboBox_status.setObjectName(u"comboBox_status")
        self.comboBox_status.setGeometry(QRect(110, 60, 180, 20))
        self.comboBox_status.setInsertPolicy(QComboBox.NoInsert)

        self.comboBox_status = QComboBox(self.page)
        self.comboBox_status.setObjectName(u"comboBox_status")
        self.comboBox_status.setGeometry(QRect(110, 60, 180, 20))
        self.comboBox_status.setInsertPolicy(QComboBox.NoInsert)

        self.pB_edit = QPushButton(self.page)
        self.pB_edit.setObjectName(u"pB_edit")
        self.pB_edit.setGeometry(QRect(50, 280, 40, 30))
        self.pB_edit.setMouseTracking(False)
        self.pB_edit.setTabletTracking(False)
        self.pB_edit.setFocusPolicy(Qt.StrongFocus)
        self.pB_edit.setAutoFillBackground(False)
        icon2 = QIcon()
        icon2.addFile("images/edit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pB_edit.setIcon(icon2)
        self.pB_edit.setCheckable(True)
        self.pB_edit.setChecked(False)
        self.pB_edit.setAutoRepeat(False)
        self.pB_edit.setAutoExclusive(False)

        # self.pushButton = QPushButton(self.page)
        # self.pushButton.setObjectName(u"pushButton")
        # self.pushButton.setGeometry(QRect(230, 280, 85, 23))

        self.pB_excel = QPushButton(self.page)
        self.pB_excel.setObjectName(u"pB_excel")
        self.pB_excel.setGeometry(QRect(540, 40, 40, 40))
        self.pB_excel.setFont(font1)
        self.pB_excel.setAutoFillBackground(False)
        icon3 = QIcon()
        icon3.addFile(u"images/excel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pB_excel.setIcon(icon3)
        self.pB_excel.setAutoRepeat(False)

        self.toolBox.addItem(self.page, "Картриджи")

        #---------------------------page_2--------------------------------#
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 580, 342))
        self.page_2.setFont(font1)
        self.page_2.setContextMenuPolicy(Qt.DefaultContextMenu)

        # self.tableView_history = QTableView(self.page_2)
        # self.tableView_history.setObjectName(u"tableView_history")
        # self.tableView_history.setGeometry(QRect(0, 100, 580, 211))
        # self.tableView_history.setToolTipDuration(0)

        self.TableWidget = QWidget(self.page_2)
        self.TableWidget.setGeometry(-8, 80, 595, 245)
        vbox = QVBoxLayout(self.TableWidget)
        self.TableWidget_History = QTableWidget()
        vbox.addWidget(self.TableWidget_History)
        self.TableWidget_History.verticalHeader().setVisible(False)

        self.comboBox_action = QComboBox(self.page_2)
        self.comboBox_action.setObjectName(u"comboBox_action")
        self.comboBox_action.setGeometry(QRect(100, 30, 180, 20))
        self.comboBox_action.setFocusPolicy(Qt.ClickFocus)
        self.comboBox_status_h = QComboBox(self.page_2)
        self.comboBox_status_h.setObjectName(u"comboBox_status_h")
        self.comboBox_status_h.setGeometry(QRect(100, 60, 180, 20))
        self.comboBox_status_h.setInsertPolicy(QComboBox.NoInsert)

        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 30, 61, 16))
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 60, 61, 16))

        self.dateEdit_min = QDateEdit(self.page_2)
        self.dateEdit_min.setObjectName(u"dateEdit_min")
        self.dateEdit_min.setGeometry(QRect(160, 0, 120, 22))
        self.dateEdit_min.setToolTipDuration(0)
        self.dateEdit_min.setWrapping(False)
        self.dateEdit_min.setReadOnly(False)
        self.dateEdit_min.setDate(datetime.today())
        self.dateEdit_min.setMinimumDate(QDate(2000, 1, 1))
        self.dateEdit_min.setMaximumTime(QTime(0, 00, 00))
        self.dateEdit_min.setCurrentSection(QDateTimeEdit.DaySection)
        self.dateEdit_min.setCalendarPopup(True)
        self.dateEdit_min.setCurrentSectionIndex(0)
        self.dateEdit_min.setTimeSpec(Qt.LocalTime)

        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 2, 26, 13))

        self.dateEdit_max = QDateEdit(self.page_2)
        self.dateEdit_max.setObjectName(u"dateEdit_max")
        self.dateEdit_max.setGeometry(QRect(370, 0, 120, 22))
        self.dateEdit_max.setAutoFillBackground(False)
        self.dateEdit_max.setAccelerated(False)
        self.dateEdit_max.setDate(datetime.today())
        self.dateEdit_max.setMinimumDate(QDate(2000, 1, 1))
        self.dateEdit_max.setMaximumTime(QTime(23, 59, 59))
        self.dateEdit_max.setCalendarPopup(True)
        self.dateEdit_max.setTimeSpec(Qt.LocalTime)

        self.pB_clear_filter_h = QPushButton(self.page_2)
        self.pB_clear_filter_h.setObjectName(u"pB_clear_filter_h")
        self.pB_clear_filter_h.setGeometry(QRect(370, 29, 121, 23))
        self.pB_clear_filter_h.setFont(font1)

        self.checkBox = QCheckBox(self.page_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(497, 0, 16, 17))
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)

        self.checkBox_All = QCheckBox(self.page_2)
        self.checkBox_All.setObjectName(u"checkBox")
        self.checkBox_All.setGeometry(QRect(44, 91, 16, 17))
        self.checkBox_All.setCheckable(True)
        self.checkBox_All.setChecked(False)

        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(100, 2, 5, 13))
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(320, 2, 12, 13))

        self.pB_print_select = QPushButton(self.page_2)
        self.pB_print_select.setObjectName(u"pB_print_select")
        self.pB_print_select.setGeometry(QRect(370, 59, 121, 23))

        self.toolBox.addItem(self.page_2, "Журнал")

        #---------------------------page_3--------------------------------#
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 580, 342))
        self.page_3.setFont(font1)

        self.dateEdit_min_otch = QDateEdit(self.page_3)
        self.dateEdit_min_otch.setObjectName(u"dateEdit_min_otch")
        self.dateEdit_min_otch.setGeometry(QRect(60, 0, 120, 22))
        dtmin = datetime.today()
        self.dateEdit_min_otch.setDateTime(dtmin)
        self.dateEdit_min_otch.setCalendarPopup(True)

        self.label_4 = QLabel(self.page_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 41, 21))
        self.label_4.setFont(font1)

        self.dateEdit_max_otch = QDateEdit(self.page_3)
        self.dateEdit_max_otch.setObjectName(u"dateEdit_max_otch")
        self.dateEdit_max_otch.setGeometry(QRect(240, 0, 120, 22))
        dtmax = datetime.today()
        self.dateEdit_max_otch.setDateTime(dtmax)
        self.dateEdit_max_otch.setCalendarPopup(True)

        self.comboBox_status_o = QComboBox(self.page_3)
        self.comboBox_status_o.setObjectName(u"comboBox_status_o")
        self.comboBox_status_o.setGeometry(QRect(60, 130, 180, 20))
        self.comboBox_status_o.setInsertPolicy(QComboBox.NoInsert)

        self.comboBox_action_o = QComboBox(self.page_3)
        self.comboBox_action_o.setObjectName(u"comboBox_action_o")
        self.comboBox_action_o.setGeometry(QRect(60, 210, 180, 20))
        self.comboBox_action_o.setFocusPolicy(Qt.ClickFocus)

        self.pushButton_3 = QPushButton(self.page_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(60, 50, 300, 23))
        self.pushButton_3.setFont(font1)

        self.pushButton_2 = QPushButton(self.page_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(60, 80, 300, 23))

        self.pushButton_4 = QPushButton(self.page_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(60, 160, 300, 23))

        self.pushButton_5 = QPushButton(self.page_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(60, 240, 300, 23))

        self.line = QFrame(self.page_3)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-10, 110, 585, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.page_3)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 190, 585, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.page_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-10, 270, 585, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.page_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(-10, 30, 585, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 4, 5, 13))
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(210, 4, 12, 13))

        self.toolBox.addItem(self.page_3, "Отчеты")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 530, 19))
        self.menuDepartments = QMenu(self.menubar)
        self.menuDepartments.setObjectName(u"menuDepartments")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.BottomToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.tableView_select, self.pB_add)
        QWidget.setTabOrder(self.pB_add, self.pB_save)
        QWidget.setTabOrder(self.pB_save, self.TableWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDepartments.menuAction())
        self.menuDepartments.addAction(self.guideModel)
        self.menuDepartments.addSeparator()
        self.menuDepartments.addAction(self.guideDepartments)
        self.menuFile.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)

        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "Учет картриджей", None))
        MainWindow.setWindowIcon(QIcon('images/iconc.jpg'))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", "Выход", None))
        # if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("MainWindow", "Alt+X", None))
        # endif // QT_CONFIG(shortcut)
        self.guideModel.setText(
            QCoreApplication.translate("MainWindow", "Модели картриджей", None))
        self.guideDepartments.setText(QCoreApplication.translate("MainWindow", "Отделения и статусы", None))
        self.pB_clear_filter.setText(QCoreApplication.translate("MainWindow", "Сбросить фильтр", None))
        self.pB_save.setText(QCoreApplication.translate("MainWindow", "Сохранить", None))
        self.pB_add.setText("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.pB_delete.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", "Номер картриджа", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", "Модель картриджа", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", "Статус", None))
        self.pB_edit.setText("")
        #self.pushButton.setText(QCoreApplication.translate("MainWindow", "Совместимость", None))
        self.pB_excel.setText("")
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("MainWindow", "Картриджи", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", "Действие", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", "Статус", None))
        self.dateEdit_min.setDisplayFormat(QCoreApplication.translate("MainWindow", "dd-MM-yyyy", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", "Дата", None))
        self.dateEdit_max.setDisplayFormat(QCoreApplication.translate("MainWindow", "dd-MM-yyyy", None))
        self.pB_clear_filter_h.setText(QCoreApplication.translate("MainWindow", "Сбросить фильтр", None))
        self.checkBox.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", "c", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", "по", None))
        self.pB_print_select.setText(
            QCoreApplication.translate("MainWindow", "Печать штрих кода", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", "Журнал", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", "Дата", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", "Движение картриджей за период", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", "Заправлено картриджей за период", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", "Отчет по статусу", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", "Отчет по действию", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", "c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", "по", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", "Отчеты", None))
        self.menuDepartments.setTitle(QCoreApplication.translate("MainWindow", "Справочники", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", "Файл", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", "toolBar", None))

    # retranslateUi


